# Generated by Django 3.0.7 on 2020-07-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=70)),
                ('email_id', models.EmailField(max_length=100)),
                ('phone_no', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
