# Generated by Django 3.0.7 on 2020-07-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200719_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='phone_no',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='user_name',
            field=models.CharField(max_length=30),
        ),
    ]
