# Generated by Django 3.0.7 on 2020-07-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200720_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
