# Generated by Django 3.0.7 on 2020-07-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200720_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
