# Generated by Django 3.0.7 on 2020-07-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200720_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='cake',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinformation',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
