# Generated by Django 3.0.7 on 2020-07-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20200727_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='quantity',
            field=models.IntegerField(default='NOT_PROVIDED'),
        ),
    ]
