# Generated by Django 3.0.7 on 2020-07-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20200727_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='cake',
            field=models.CharField(max_length=600),
        ),
    ]
