# Generated by Django 3.0.7 on 2020-07-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_userinformation_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
