# Generated by Django 3.0.7 on 2020-07-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_userinformation_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
