# Generated by Django 3.0.7 on 2020-07-27 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20200727_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='quantity',
        ),
    ]
