# Generated by Django 3.0.7 on 2020-07-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_remove_userinformation_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='cake',
        ),
    ]
