# Generated by Django 3.0.7 on 2020-07-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_remove_userinformation_cake'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='quantity',
            field=models.IntegerField(default=100),
        ),
    ]
