# Generated by Django 3.0.7 on 2020-07-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20200727_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='cake',
            field=models.CharField(default='not have', max_length=100),
        ),
    ]
